DIGITS Attendance Monitoring System/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OfficerLoginSignUpController;
use App\Http\Controllers\OfficerDashboardController;
use App\Http\Controllers\OfficerStudentListController;
use App\Http\Controllers\OfficerStudentReportController;
use App\Http\Controllers\OfficerEventAttendanceController;
use App\Http\Controllers\OfficerEventSelectedController;
use App\Http\Controllers\OfficerScanController;
use App\Http\Controllers\OfficerEventController;
use App\Http\Controllers\OfficerAccountManagementController;
use App\Http\Controllers\OfficerAnnouncementController;

use App\Http\Controllers\StudentLoginSignUpController;
use App\Http\Controllers\StudentSignUpSupportController;
use App\Http\Controllers\StudentDashboardController;
use App\Http\Controllers\StudentQrcodeController;
use App\Http\Controllers\StudentAttendanceReportController;
use App\Http\Controllers\StudentEventsController;
use App\Http\Controllers\StudentAccountManagementController;
use App\Http\Controllers\StudentUpdateProfileController;

use App\Http\Controllers\AttendanceController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    /**This line will redirect to officer sign in page. */
    //return redirect('/officer');
    /**This line will redirect to student sign in page. */
    return redirect('/student');
});

Route::get('/student', function () {
    return redirect('/student-signin');
});

Route::get('/student-signin', function () {
    if(session()->has('sid')){
        return redirect()->route(session('student-location').'.index');
    }else{
        return view('credentials.student-sign-in');     
    }
});

Route::get('/student-logout', function () {
    session()->forget('sid');
    session()->forget('student-location');
    return redirect('/student-signin');
});

Route::get('/officer', function () {
    return redirect('/officer-signin');
});

Route::get('/officer-signin', function () {
    if(session()->has('oid')){
        return redirect()->route(session('officer-location').'.index');
    }else{
        return view('credentials.officer-sign-in');
    }
});

Route::get('/officer-logout', function () {
    session()->forget('oid');
    session()->forget('officer-location');
    return redirect('/officer-signin');
});

Route::get('/officer-sl', function () {
    $ys = ["All","All"];
    session()->put('ys', $ys);
    return redirect('/officer-studentlist');
});

Route::get('/officer-ea', function () {
    $eid = "";
    session()->put('eid', $eid);
    return redirect('/officer-eventattendance');
});
/*
Route::get('/officer-eventattendance/officer-ea', function () {
    $eid = "";
    session()->put('eid', $eid);
    return redirect('/officer-eventattendance');
});
*/
Route::resource('/officer-signup', OfficerLoginSignUpController::class);
Route::resource('/officer-dashboard', OfficerDashboardController::class);
Route::resource('/officer-studentlist', OfficerStudentListController::class);
Route::resource('/officer-studentreport', OfficerStudentReportController::class);
Route::resource('/officer-eventattendance', OfficerEventAttendanceController::class);
Route::resource('/officer-eventattendance-selected', OfficerEventSelectedController::class);
Route::resource('/officer-scan', OfficerScanController::class);
Route::resource('/officer-event', OfficerEventController::class);
Route::resource('/officer-accountmanagement', OfficerAccountManagementController::class);
Route::resource('/officer-announcement', OfficerAnnouncementController::class);

Route::resource('/student-signup', StudentLoginSignUpController::class);
Route::resource('/student-signup-support', StudentSignUpSupportController::class);
Route::resource('/student-dashboard', StudentDashboardController::class);
Route::resource('/student-qrcode', StudentQrcodeController::class);
Route::resource('/student-attendancereport', StudentAttendanceReportController::class);
Route::resource('/student-event', StudentEventsController::class);
Route::resource('/student-accountmanagement', StudentAccountManagementController::class);
Route::resource('/student-updateprofile', StudentUpdateProfileController::class);

Route::resource('/attendance', AttendanceController::class);

DIGITS Attendance Monitoring System/resources/views/credentials/officer-sign-in.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/officer-css.php"?>
</head>
    <body>
        <div>
            <div class="row">
                <div class="cred-con-in">
                    <div class="col pt-5 pr-4 pl-4">
                        <div class="cred-header">
                            <img src="../addons/assets/img/icon1.png" alt="">
                            <div>
                                <h2>DIGITS</h2>
                                <h3>Attendance Monitoring System</h3>
                            </div>
                        </div>
                        <form action="{{ route('officer-signup.show','0') }}" method="get">
                            @csrf
                            @method('get')
                            <h5><span class="fa fa-user"></span> OFFICER SIGN IN</h5>
                            <div class="form-group">
                                <input type="text" placeholder="Username" name="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="password" placeholder="Password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-sign-in"></span> Sign In</button>
                            </div>
                        </form>
                        <div class="col" style="text-align: right;">
                            <h6>Don't have an account? <a href="{{ url('officer-signup') }}">Sign Up</a></h6>
                        </div>
                    </div><?php include "addons/includes/master-js.php"?>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('officer-message')){
                    echo session("officer-message")[0].'("'.session("officer-message")[1].'")';
                    session()->forget('officer-message'); 
                }
            ?>
        </script>
    </body>
</html>

DIGITS Attendance Monitoring System/resources/views/credentials/officer-sign-up.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/officer-css.php"?>
</head>
    <body>
        <div>
            <div class="row">
                <div class="cred-con-up">
                    <div class="col pt-5 pr-4 pl-4 p-5">
                    <div class="cred-header">
                            <img src="../addons/assets/img/icon1.png" alt="">
                            <div>
                                <h2>DIGITS</h2>
                                <h3>Attendance Monitoring System</h3>
                            </div>
                        </div>
                        <form action="{{ route('officer-signup.store') }}" method="post">
                            @csrf 
                            @method('post')
                            <h5><span class="fa fa-user"></span> OFFICER SIGN UP</h5>
                            <div class="form-group">
                                <label for="">Student No. (This will serve as username.)</label>
                                <input required type="number" name="stuid" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <label for="">Last Name</label>
                                        <input required type="text" name="lname" class="form-control">
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">First Name</label>
                                        <input required type="text" name="fname" class="form-control">
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">MI</label>
                                        <input required type="text" name="mi" class="form-control">    
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Age</label>
                                        <input required type="number" name="age" class="form-control">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Birth Date</label>
                                        <input required type="date" name="bday" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Address</label>
                                <input required type="text" name="address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Email</label>
                                <input required type="email" name="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Year</label>
                                        <select required name="year" id="" class="form-control">
                                            @foreach($year as $y)
                                                <option value="{{ $y->yname }}">{{ $y->yname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Section</label>
                                        <select required name="section" id="" class="form-control">
                                            @foreach($section as $s)
                                                <option value="{{ $s->sname }}">{{ $s->sname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Position</label>
                                <select required name="position" id="" class="form-control">
                                    @foreach($position as $p)
                                        <option value="{{ $p->pname }}">{{ $p->pname }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label for="">Create New Password</label>
                                <input required type="password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Retype Password</label>
                                <input required type="password" name="repassword" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success col"><span class="fa fa-sign-in"></span> Submit</button>
                            </div>
                        </form>
                        <div class="col" style="text-align: right;">
                            <h6>Already have an account? <a href="{{ url('officer-signin') }}">Sign In</a></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('officer-message')){
                    echo session("officer-message")[0].'("'.session("officer-message")[1].'")';
                    session()->forget('officer-message'); 
                }
            ?>
        </script>
    </body>
</html>

DIGITS Attendance Monitoring System/resources/views/credentials/student-sign-in.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/student-css.php"?>
</head>
    <body>
        <div>
            <div class="row">
                <div class="cred-con-in">
                    <div class="col pt-5 pr-4 pl-4">
                        <div class="cred-header">
                            <img src="../addons/assets/img/icon1.png" alt="">
                            <div>
                                <h2>DIGITS</h2>
                                <h3>Attendance Monitoring System</h3>
                            </div>
                        </div>
                        <form action="{{ route('student-signup.show','0') }}" method="get">
                            @csrf
                            @method('get')
                            <h5><span class="fa fa-user"></span> STUDENT SIGN IN</h5>
                            <div class="form-group">
                                <input type="text" placeholder="Username" name="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="password" placeholder="Password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-sign-in"></span> Sign In</button>
                            </div>
                        </form>
                        <div class="col" style="text-align: right;">
                            <h6>Don't have an account? <a href="{{ url('student-signup') }}">Sign Up</a></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('student-message')){
                    echo session("student-message")[0].'("'.session("student-message")[1].'")';
                    session()->forget('student-message'); 
                }
            ?>
        </script>
    </body>
</html>

DIGITS Attendance Monitoring System/resources/views/credentials/student-sign-up.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/student-css.php"?>
</head>
    <body>
        <div>
            <div class="row">
                <div class="cred-con-up">
                    <div class="col pt-5 pr-4 pl-4 p-5">
                        <div class="cred-header">
                            <img src="../addons/assets/img/icon1.png" alt="">
                            <div>
                                <h2>DIGITS</h2>
                                <h3>Attendance Monitoring System</h3>
                            </div>
                        </div>
                        <form action="addons/qrcode_support/qrcode.php" method="post">
                            @csrf 
                            @method('post')
                            <h5><span class="fa fa-user"></span> STUDENT SIGN UP</h5>
                            <div class="form-group">
                                <label for="">Student No. (This will serve as username.)</label>
                                <input required type="number" name="stuid" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <label for="">Last Name</label>
                                        <input required type="text" name="lname" class="form-control">
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">First Name</label>
                                        <input required type="text" name="fname" class="form-control">
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">MI</label>
                                        <input required type="text" name="mi" class="form-control">    
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Age</label>
                                        <input required type="number" name="age" class="form-control">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Birth Date</label>
                                        <input required type="date" name="bday" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Address</label>
                                <input required type="text" name="address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Email</label>
                                <input required type="email" name="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Year</label>
                                        <select required name="year" id="" class="form-control">
                                            @foreach($year as $y)
                                                <option value="{{ $y->yname }}">{{ $y->yname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Section</label>
                                        <select required name="section" id="" class="form-control">
                                            @foreach($section as $s)
                                                <option value="{{ $s->sname }}">{{ $s->sname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label for="">Create New Password</label>
                                <input required type="password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Retype Password</label>
                                <input required type="password" name="repassword" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success col"><span class="fa fa-sign-in"></span> Submit</button>
                            </div>
                        </form>
                        <div class="col" style="text-align: right;">
                            <h6>Already have an account? <a href="{{ url('student-signin') }}">Sign In</a></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('student-message')){
                    echo session("student-message")[0].'("'.session("student-message")[1].'")';
                    session()->forget('student-message'); 
                }
            ?>
        </script>
    </body>
</html>