DIGITS Attendance Monitoring System/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OfficerLoginSignUpController;
use App\Http\Controllers\OfficerDashboardController;
use App\Http\Controllers\OfficerStudentListController;
use App\Http\Controllers\OfficerStudentReportController;
use App\Http\Controllers\OfficerEventAttendanceController;
use App\Http\Controllers\OfficerEventSelectedController;
use App\Http\Controllers\OfficerScanController;
use App\Http\Controllers\OfficerEventController;
use App\Http\Controllers\OfficerAccountManagementController;
use App\Http\Controllers\OfficerAnnouncementController;

use App\Http\Controllers\StudentLoginSignUpController;
use App\Http\Controllers\StudentSignUpSupportController;
use App\Http\Controllers\StudentDashboardController;
use App\Http\Controllers\StudentQrcodeController;
use App\Http\Controllers\StudentAttendanceReportController;
use App\Http\Controllers\StudentEventsController;
use App\Http\Controllers\StudentAccountManagementController;
use App\Http\Controllers\StudentUpdateProfileController;

use App\Http\Controllers\AttendanceController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    /**This line will redirect to officer sign in page. */
    //return redirect('/officer');
    /**This line will redirect to student sign in page. */
    return redirect('/student');
});

Route::get('/student', function () {
    return redirect('/student-signin');
});

Route::get('/student-signin', function () {
    if(session()->has('sid')){
        return redirect()->route(session('student-location').'.index');
    }else{
        return view('credentials.student-sign-in');     
    }
});

Route::get('/student-logout', function () {
    session()->forget('sid');
    session()->forget('student-location');
    return redirect('/student-signin');
});

Route::get('/officer', function () {
    return redirect('/officer-signin');
});

Route::get('/officer-signin', function () {
    if(session()->has('oid')){
        return redirect()->route(session('officer-location').'.index');
    }else{
        return view('credentials.officer-sign-in');
    }
});

Route::get('/officer-logout', function () {
    session()->forget('oid');
    session()->forget('officer-location');
    return redirect('/officer-signin');
});

Route::get('/officer-sl', function () {
    $ys = ["All","All"];
    session()->put('ys', $ys);
    return redirect('/officer-studentlist');
});

Route::get('/officer-ea', function () {
    $eid = "";
    session()->put('eid', $eid);
    return redirect('/officer-eventattendance');
});
/*
Route::get('/officer-eventattendance/officer-ea', function () {
    $eid = "";
    session()->put('eid', $eid);
    return redirect('/officer-eventattendance');
});
*/
Route::resource('/officer-signup', OfficerLoginSignUpController::class);
Route::resource('/officer-dashboard', OfficerDashboardController::class);
Route::resource('/officer-studentlist', OfficerStudentListController::class);
Route::resource('/officer-studentreport', OfficerStudentReportController::class);
Route::resource('/officer-eventattendance', OfficerEventAttendanceController::class);
Route::resource('/officer-eventattendance-selected', OfficerEventSelectedController::class);
Route::resource('/officer-scan', OfficerScanController::class);
Route::resource('/officer-event', OfficerEventController::class);
Route::resource('/officer-accountmanagement', OfficerAccountManagementController::class);
Route::resource('/officer-announcement', OfficerAnnouncementController::class);

Route::resource('/student-signup', StudentLoginSignUpController::class);
Route::resource('/student-signup-support', StudentSignUpSupportController::class);
Route::resource('/student-dashboard', StudentDashboardController::class);
Route::resource('/student-qrcode', StudentQrcodeController::class);
Route::resource('/student-attendancereport', StudentAttendanceReportController::class);
Route::resource('/student-event', StudentEventsController::class);
Route::resource('/student-accountmanagement', StudentAccountManagementController::class);
Route::resource('/student-updateprofile', StudentUpdateProfileController::class);

Route::resource('/attendance', AttendanceController::class);

DIGITS Attendance Monitoring System/resources/views/officer/event-attendance.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/officer-css.php"?>
</head>
    <body>
        <?php include "addons/navigations/officer-sidebar.php"?>
        <div class="display-container">
            <div class="table-container">
                <div class="row">
                    <div class="col-md-5">
                        <div class="card-list">
                            <div class="modal-header">
                                <h6><span class="fa fa-list"></span> School Events List</h6>
                            </div>
                            <table class="table-hover">
                                <tbody>
                                    @foreach($event as $e)
                                        @if($eventselected[0]->eid == $e->eid)
                                            <tr>
                                                <td style="display: flex; justify-content: space-between;" class="col">
                                                    <a class="event-list" href="{{ route('officer-eventattendance.show',$e->id) }}"><b>{{ $e->name }}</b></a>
                                                    <a class="btn btn-primary btn-sm" href="{{ route('officer-scan.show',$e->eid) }}"><span class="fa fa-qrcode"></span> Scan</a>
                                                </td>
                                            </tr>
                                        @else
                                            <tr>
                                                <td style="display: flex; justify-content: space-between;" class="col">
                                                    <a class="event-list" href="{{ route('officer-eventattendance.show',$e->id) }}"><b>{{ $e->name }}</b></a>
                                                    <a class="btn btn-secondary btn-sm" href="{{ route('officer-scan.show',$e->eid) }}"><span class="fa fa-qrcode"></span> Scan</a>
                                                </td>
                                            </tr>
                                        @endif
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="card-list">
                            <div class="modal-header">
                                <h6><span class="fa fa-calendar"></span> {{ session('event-name') }} Attendance List</h6>
                            </div>
                            <table>
                                <thead>
                                    <tr>
                                        <td>Profile</td>
                                        <td>Student Info</td>
                                        <td>Morning</td>
                                        <td>Afternoon</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($eventselected as $es)
                                        @foreach($studentattendance as $sa)
                                            @if($es->eid == $sa->eid)
                                                @foreach($student as $st)
                                                    @if($sa->sid == $st->sid)
                                                        <tr>
                                                            <td style="text-align: center;">
                                                                <img class="student-profile" src="../addons/assets/root/profiles/{{ $st->profile }}" alt="">
                                                            </td>
                                                            <td>
                                                                <h6><b>Student No.: </b>{{ $st->stuid }}</h6>
                                                                <h6><b>Name: </b>{{ $st->lname }}, {{ $st->fname }} {{ $st->mi }}.</h6>
                                                            </td>
                                                            <td>
                                                                <h6><b>In: <span style="color: green; padding: 3px;">{{ $sa->min }}</span></b></h6>
                                                                <h6><b>Out: <span style="color: blue; padding: 3px;">{{ $sa->mout }}</span></b></h6>
                                                            </td>
                                                            <td>
                                                                <h6><b>In: <span style="color: green; padding: 3px;">{{ $sa->ain }}</span></b></h6>
                                                                <h6><b>Out: <span style="color: blue; padding: 3px;">{{ $sa->aout }}</span></b></h6>
                                                            </td>
                                                        </tr>
                                                    @endif
                                                @endforeach
                                            @endif
                                        @endforeach
                                    @endforeach
                                </tbody>
                            </table>    
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="accountmanagement">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <form action="{{ route('officer-accountmanagement.update',$info[0]->id) }}" method="post">
                            @csrf 
                            @method('put')
                            <h5><span class="fa fa-gears"></span> Account Management</h5>
                            <div class="form-group">
                                <label for="">Student No.</label>
                                <input required readonly value="{{ $info[0]->stuid }}" type="number" name="stuid" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <label for="">Last Name</label>
                                        <input required value="{{ $info[0]->lname }}" type="text" name="lname" class="form-control">
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">First Name</label>
                                        <input required value="{{ $info[0]->fname }}" type="text" name="fname" class="form-control">
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">MI</label>
                                        <input required value="{{ $info[0]->mi }}" type="text" name="mi" class="form-control">    
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Age</label>
                                        <input required value="{{ $info[0]->age }}" type="number" name="age" class="form-control">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Birth Date</label>
                                        <input required value="{{ $info[0]->birthdate }}" type="date" name="bday" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Address</label>
                                <input required value="{{ $info[0]->address }}" type="text" name="address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Email</label>
                                <input required value="{{ $info[0]->email }}" type="email" name="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Year</label>
                                        <select required name="year" id="" class="form-control">
                                            <option  value="{{ $info[0]->year }}">{{ $info[0]->year }}</option>
                                            @foreach($year as $y)
                                                <option value="{{ $y->yname }}">{{ $y->yname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Section</label>
                                        <select required name="section" id="" class="form-control">
                                        <option  value="{{ $info[0]->section }}">{{ $info[0]->section }}</option>
                                            @foreach($section as $s)
                                                <option value="{{ $s->sname }}">{{ $s->sname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Position</label>
                                <select required name="position" id="" class="form-control">
                                    <option  value="{{ $info[0]->position }}">{{ $info[0]->position }}</option>
                                    @foreach($position as $p)
                                        <option value="{{ $p->pname }}">{{ $p->pname }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-save"></span> Save Changes</button>
                            </div>
                        </form>
                        <hr>
                        <form action="{{ route('officer-signup.update',$info[0]->oid) }}" method="post">
                            @csrf 
                            @method('put')
                            <div class="form-group">
                                <label for="">Create New Password</label>
                                <input required type="password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Retype Password</label>
                                <input required type="password" name="repassword" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-save"></span> Save Password</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('officer-message')){
                    echo session("officer-message")[0].'("'.session("officer-message")[1].'")';
                    session()->forget('officer-message'); 
                }
            ?>
        </script>
    </body>
    
</html>

DIGITS Attendance Monitoring System/resources/views/officer/scan.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/officer-css.php"?>
</head>
    <body>
        <div class="table-container">
            <div class="row card-list">
                <div class="modal-header col">
                    <h4><span class="fa fa-qrcode"></span> {{ $event[0]->name }} Attendance</h4>
                    <input id="eid" type="hidden" value="{{ $event[0]->eid }}">
                    <div class="timeDate row">
                        <h5 id="date" class="mr-3">May 25, 2019 Thursday</h5>|              
                        <h5 id="time" class="ml-3" style="text-transform: uppercase;">17:56 PM</h5>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row card-list" style="text-align: center;">
                <div class="col">
                    <input type="hidden" name="" id="d">
                    <input type="hidden" name="" id="t">    
                    <input type="hidden" name="" id="ampm">    
                    <div class="scan-container mt-3">
                       <video id="preview"></video> 
                    </div>
                </div>
            </div>
            <hr>
            <div class="row card-list p-3" id="profileres">
                <div class="col-md-3">
                    <div class="attendance-card mb-4">
                        <img src="../addons/assets/root/profiles/default.png" alt="">
                        <div>
                            <h6><b>Student No.: </b>xxxxxxx</h6>
                            <h6><b>Name: </b>...</h6>
                            <h6><b>Year & Section: </b>...</h6>
                        </div>
                    </div>    
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            setInterval(startTime(), 1000);

            function startTime() {
                // declare array for month
                var monthList = ["Null","January","Febuary","March","April","May","June","July","August","September","October","November","December"]
                // create new object for Date
                var today = new Date();
                // format hour to 24 hour format
                today.toLocaleString('en-US', { hour: 'numeric', hour12: true });
                // get time
                var hours = today.getHours();
                var minutes = today.getMinutes();
                var seconds = today.getSeconds();
                // get am or pm
                var ampm = hours >= 12 ? 'pm' : 'am';
                // get hour for 12 hour format
                hours = hours % 12;
                hours = hours ? hours : 12;
                // get month
                var month = today.getMonth() + 1;
                var day = today.getDate();
                var year = today.getFullYear();
                // add 0 to time if time < 10
                minutes = checkTime(minutes);
                seconds = checkTime(seconds);
                // display date and time
                document.getElementById('time').innerHTML = hours + ":" + minutes + ":" + seconds + " " + ampm;
                document.getElementById('date').innerHTML = monthList[month] + " " + day + " ," + year;
                // ready time for attendance
                document.getElementById('t').value = hours + ":" + minutes + ":" + seconds;
                document.getElementById('d').value = year + "-" + month + "-" + day;
                document.getElementById('ampm').value = ampm;
                // set timeout after execution
                var t = setTimeout(startTime, 500);
            }
            function checkTime(i) {
                if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
                return i;
            }


            /**
             * Qrcode scanning and attendance process
             */
            function sub(){
                var t = document.getElementById('t').value;
                var d = document.getElementById('d').value;
                var ampm = document.getElementById('ampm').value;

                window.location.href = "../" + "?date=" + d + "&time=" + t + "&ampm=" + ampm;
            }
            Instascan.Camera.getCameras().then(function (cameras){
                if(cameras.length>0){
                    scanner.start(cameras[0]);
                    /*$('[name="options"]').on('change',function(){
                        if($(this).val()==1){
                            if(cameras[0]!=""){
                                scanner.start(cameras[0]);
                            }else{
                                alert('No Front camera found!');
                            }
                        }else if($(this).val()==2){
                            if(cameras[1]!=""){
                                scanner.start(cameras[1]);
                            }else{
                                alert('No Back camera found!');
                            }
                        }
                    });*/
                }else{
                    console.error('No cameras found.');
                    alert('No cameras found.');
                }
            }).catch(function(e){
                console.error(e);
                console.log(e);
            });
            var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: true });
            scanner.addListener('scan',function(content){
                console.log(content)
                var myArray = content.split(".");
                if(myArray[0] != "DIGITS"){
                    toastr.options = {
                        "closeButton": true,
                        "newestOnTop": true,
                        "progressBar": true,
                        "positionClass": "toast-bottom-right",
                    }
                    var audio = new Audio('../addons/assets/sound/wapking.mp3');
                    audio.play();
                    toastr.warning("Invalid QRcode");
                }else{
                    console.log(content);
                    var sid = myArray[2];
                    fetch('../api/getscanresult')
                    .then(response => response.json())
                    .then(response => displayProfile(response, sid))
                    .catch(err => console.log('Request Failed', err));
                }
                
            });


            function displayProfile(data, sid){
                console.log(data[1])
                var index = data[1];
                var i = 0;

                while(i <= index){
                    if(sid == data[0][i].sid){
                        var a = document.getElementById("profileres");
                        a.insertAdjacentHTML('afterbegin', '<div class="col-md-3 mb-4"><div class="attendance-card"><img src="../addons/assets/root/profiles/'+ data[0][i].profile +'" alt=""><div><h6><b>Student No.: </b>'+ data[0][i].stuid +'</h6><h6><b>Name: </b>'+ data[0][i].lname + ', '+ data[0][i].fname + ' ' + data[0][i].mi + '.' +'</h6><h6><b>Yr. & Sec.: </b>'+ data[0][i].year + ' - ' + data[0][i].section +'</h6></div></div></div>');
                        var audio = new Audio('../addons/assets/sound/wapking.mp3');
                        audio.play();
                        attendance(sid);
                    }
                    i++;
                }
            }
            function attendance(sid){
                toastr.options = {
                    "closeButton": true,
                    "newestOnTop": true,
                    "progressBar": true,
                    "positionClass": "toast-bottom-left",
                }
                var eid = document.getElementById('eid').value;
                var t = document.getElementById('t').value;
                var d = document.getElementById('d').value;
                var ampm = document.getElementById('ampm').value;
                var data = sid + "_" + d + "_" + t + '_' + ampm + '_' + eid;
                fetch('../addons/attendance_support/attendance.php', {
                    method: 'POST',
                    body: new URLSearchParams('data=' + data)
                })
                .then(res => res.json())
                .then(res => popup(res))
                .catch(e => toastr.warning("Invalid QR Code"))
            }
            function popup(res){
                toastr.options = {
                    "closeButton": true,
                    "newestOnTop": true,
                    "progressBar": true,
                    "positionClass": "toast-bottom-right",
                }
                var type = res[0];
                var message = res[1];

                if(type == "warning"){
                    toastr.warning(message);
                }
                if(type == "info"){
                    toastr.info(message);
                }
                if(type == "success"){
                    toastr.success(message);
                }
                if(type == "error"){
                    toastr.error(message);
                }
            }
        </script>
    </body>
    
</html>

DIGITS Attendance Monitoring System/resources/views/officer/studentreport.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/officer-css.php"?>
</head>
    <body>
        <div class="table-container">
            <div class="card-list col" style="width: 700px; margin: auto;">
                <div class="row col" style="display: flex; justify-content: space-between;">
                    <h5><span class="fa fa-calendar"></span> Attendance Reports</h5>
                    <button class="btn btn-primary btn-sm" onclick="printCard('card')"><span class="fa fa-print"></span> Print</button>
                </div>
                <hr>
                <div id="card">
                    <div class="row">
                        <div class="attendance-card col" style="box-shadow: none !important;">
                            <img src="../addons/assets/root/profiles/{{ $info[0]->profile }}" style="width: 100px !important; height: 110px !important;" alt="">
                            <div>
                                <h6><b>Student No.: </b>{{ $info[0]->stuid }}</h6>
                                <h6><b>Name: </b>{{ $info[0]->lname }}, {{ $info[0]->fname }} {{ $info[0]->mi }}.</h6>
                                <h6><b>Year & Section: </b>{{ $info[0]->year }} - {{ $info[0]->section }}</h6>
                                <h6><b>Number of Days Absent: </b>{{ $sanction }} Day/s</h6>
                            </div>
                        </div> 
                    </div> 
                    <hr>
                    <div class="row">
                        <table>
                            <thead>
                                <tr>
                                    <td>Event Name</td>
                                    <td>Date</td>
                                    <td>Morning</td>
                                    <td>Afternoon</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($studentattendance as $sa)
                                    @foreach($event as $e)
                                        @if($e->eid == $sa->eid)
                                        <tr>
                                            <td><h6>{{ $e->name }}</h6></td>
                                            <td><h6>{{ date('M d, Y', strtotime($e->date)) }}</h6></td>
                                            <td>
                                                <h6><b>Time In: </b>{{ $sa->min }}</h6>
                                                <h6><b>Time Out: </b>{{ $sa->mout }}</h6>
                                            </td>
                                            <td>
                                                <h6><b>Time In: </b>{{ $sa->ain }}</h6>
                                                <h6><b>Time Out: </b>{{ $sa->aout }}</h6>
                                            </td>
                                        </tr>
                                        @endif
                                    @endforeach
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('officer-message')){
                    echo session("officer-message")[0].'("'.session("officer-message")[1].'")';
                    session()->forget('officer-message'); 
                }
            ?>
        </script>
    </body>
    
</html>