DIGITS Attendance Monitoring System/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OfficerLoginSignUpController;
use App\Http\Controllers\OfficerDashboardController;
use App\Http\Controllers\OfficerStudentListController;
use App\Http\Controllers\OfficerStudentReportController;
use App\Http\Controllers\OfficerEventAttendanceController;
use App\Http\Controllers\OfficerEventSelectedController;
use App\Http\Controllers\OfficerScanController;
use App\Http\Controllers\OfficerEventController;
use App\Http\Controllers\OfficerAccountManagementController;
use App\Http\Controllers\OfficerAnnouncementController;

use App\Http\Controllers\StudentLoginSignUpController;
use App\Http\Controllers\StudentSignUpSupportController;
use App\Http\Controllers\StudentDashboardController;
use App\Http\Controllers\StudentQrcodeController;
use App\Http\Controllers\StudentAttendanceReportController;
use App\Http\Controllers\StudentEventsController;
use App\Http\Controllers\StudentAccountManagementController;
use App\Http\Controllers\StudentUpdateProfileController;

use App\Http\Controllers\AttendanceController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    /**This line will redirect to officer sign in page. */
    //return redirect('/officer');
    /**This line will redirect to student sign in page. */
    return redirect('/student');
});

Route::get('/student', function () {
    return redirect('/student-signin');
});

Route::get('/student-signin', function () {
    if(session()->has('sid')){
        return redirect()->route(session('student-location').'.index');
    }else{
        return view('credentials.student-sign-in');     
    }
});

Route::get('/student-logout', function () {
    session()->forget('sid');
    session()->forget('student-location');
    return redirect('/student-signin');
});

Route::get('/officer', function () {
    return redirect('/officer-signin');
});

Route::get('/officer-signin', function () {
    if(session()->has('oid')){
        return redirect()->route(session('officer-location').'.index');
    }else{
        return view('credentials.officer-sign-in');
    }
});

Route::get('/officer-logout', function () {
    session()->forget('oid');
    session()->forget('officer-location');
    return redirect('/officer-signin');
});

Route::get('/officer-sl', function () {
    $ys = ["All","All"];
    session()->put('ys', $ys);
    return redirect('/officer-studentlist');
});

Route::get('/officer-ea', function () {
    $eid = "";
    session()->put('eid', $eid);
    return redirect('/officer-eventattendance');
});
/*
Route::get('/officer-eventattendance/officer-ea', function () {
    $eid = "";
    session()->put('eid', $eid);
    return redirect('/officer-eventattendance');
});
*/
Route::resource('/officer-signup', OfficerLoginSignUpController::class);
Route::resource('/officer-dashboard', OfficerDashboardController::class);
Route::resource('/officer-studentlist', OfficerStudentListController::class);
Route::resource('/officer-studentreport', OfficerStudentReportController::class);
Route::resource('/officer-eventattendance', OfficerEventAttendanceController::class);
Route::resource('/officer-eventattendance-selected', OfficerEventSelectedController::class);
Route::resource('/officer-scan', OfficerScanController::class);
Route::resource('/officer-event', OfficerEventController::class);
Route::resource('/officer-accountmanagement', OfficerAccountManagementController::class);
Route::resource('/officer-announcement', OfficerAnnouncementController::class);

Route::resource('/student-signup', StudentLoginSignUpController::class);
Route::resource('/student-signup-support', StudentSignUpSupportController::class);
Route::resource('/student-dashboard', StudentDashboardController::class);
Route::resource('/student-qrcode', StudentQrcodeController::class);
Route::resource('/student-attendancereport', StudentAttendanceReportController::class);
Route::resource('/student-event', StudentEventsController::class);
Route::resource('/student-accountmanagement', StudentAccountManagementController::class);
Route::resource('/student-updateprofile', StudentUpdateProfileController::class);

Route::resource('/attendance', AttendanceController::class);

DIGITS Attendance Monitoring System/resources/views/student/attendancereport.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/student-css.php"?>
</head>
    <body>
        <?php include "addons/navigations/student-sidebar.php"?>
        <div class="display-container">
            <div class="table-container">
                <div class="card-list">
                    <div class="row modal-header">
                        <h6><span class="fa fa-calendar"></span> Attendance Report</h6>
                    </div>
                    <div class="row">
                        <table>
                            <thead>
                                <tr>
                                    <td>Event Name</td>
                                    <td>Date</td>
                                    <td>Morning</td>
                                    <td>Afternoon</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($studentattendance as $sa)
                                    @foreach($event as $e)
                                        @if($e->eid == $sa->eid)
                                        <tr>
                                            <td><h6>{{ $e->name }}</h6></td>
                                            <td><h6>{{ date('M d, Y', strtotime($e->date)) }}</h6></td>
                                            <td>
                                                <h6><b>Time In: </b>{{ $sa->min }}</h6>
                                                <h6><b>Time Out: </b>{{ $sa->mout }}</h6>
                                            </td>
                                            <td>
                                                <h6><b>Time In: </b>{{ $sa->ain }}</h6>
                                                <h6><b>Time Out: </b>{{ $sa->aout }}</h6>
                                            </td>
                                        </tr>
                                        @endif
                                    @endforeach
                                @endforeach
                            </tbody>
                        </table> 
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="accountmanagement">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <form action="{{ route('student-accountmanagement.update',$info[0]->id) }}" method="post">
                            @csrf 
                            @method('put')
                            <h5><span class="fa fa-gears"></span> Account Management</h5>
                            <hr>
                            <div class="form-group view-student-profile">
                                <img class="cover" src="../addons/assets/img/table1.png" alt="">
                                <img class="profile" src="../addons/assets/root/profiles/{{ $info[0]->profile }}" alt="">
                            </div> 
                            <div class="form-group">
                                <label for="">Student No.</label>
                                <input required readonly value="{{ $info[0]->stuid }}" type="number" name="stuid" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <label for="">Last Name</label>
                                        <input required value="{{ $info[0]->lname }}" type="text" name="lname" class="form-control">
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">First Name</label>
                                        <input required value="{{ $info[0]->fname }}" type="text" name="fname" class="form-control">
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">MI</label>
                                        <input required value="{{ $info[0]->mi }}" type="text" name="mi" class="form-control">    
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Age</label>
                                        <input required value="{{ $info[0]->age }}" type="number" name="age" class="form-control">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Birth Date</label>
                                        <input required value="{{ $info[0]->birthdate }}" type="date" name="bday" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Address</label>
                                <input required value="{{ $info[0]->address }}" type="text" name="address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Email</label>
                                <input required value="{{ $info[0]->email }}" type="email" name="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Year</label>
                                        <select required name="year" id="" class="form-control">
                                            <option selected value="{{ $info[0]->year }}">{{ $info[0]->year }}</option>
                                            @foreach($year as $y)
                                                <option value="{{ $y->yname }}">{{ $y->yname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Section</label>
                                        <select required name="section" id="" class="form-control">
                                            <option selected  value="{{ $info[0]->section }}">{{ $info[0]->section }}</option>
                                            @foreach($section as $s)
                                                <option value="{{ $s->sname }}">{{ $s->sname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-save"></span> Save Changes</button>
                            </div>
                        </form>
                        <hr>
                        <form action="{{ route('student-signup.update',$info[0]->sid )}}" method="post">
                            @csrf 
                            @method('put')
                            <div class="form-group">
                                <label for="">Create New Password</label>
                                <input required type="password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Retype Password</label>
                                <input required type="password" name="repassword" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-save"></span> Save Password</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="profilepicture">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <form action="../addons/file_upload_support/uploadProfile.php?id={{ $info[0]->id }}&profile={{ $info[0]->profile }}" method="POST" enctype="multipart/form-data">
                            <div class="modal-body" style="padding: 10px;">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">Upload</span>
                                        </div>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="new_profile" id="upload" onchange="displayname(this,$(this))">
                                            <label class="custom-file-label" for="upload">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary btn-sm"><span class="fa fa-save"></span> Save</button>
                                <button data-dismiss="modal" class="btn btn-dark btn-sm"><span class="fa fa-times"></span> Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('student-message')){
                    echo session("student-message")[0].'("'.session("student-message")[1].'")';
                    session()->forget('student-message'); 
                }
            ?>
        </script>
    </body>
</html>

DIGITS Attendance Monitoring System/resources/views/student/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DIGITS Attendance Monitoring System</title>
    <?php include "addons/includes/master-css.php"?>
    <?php include "addons/includes/master-js.php"?>
    <?php include "addons/includes/student-css.php"?>
</head>
    <body>
        <?php include "addons/navigations/student-sidebar.php"?>
        <div class="display-container">
            <div class="table-container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="con-a modal-header card-list">
                            <div>
                                <h5>{{ $s }}</h5>
                                <h6>Total Number of Students</h6>
                            </div>
                            <span class="fa fa-users"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="con-b modal-header card-list">
                            <div>
                                <h5>{{ $e }}</h5>
                                <h6>Events</h6>
                            </div>
                            <span class="fa fa-users"></span>
                        </div>
                    </div>
                    <div class="col-md-4 ">
                        <div class="con-c modal-header card-list">
                            <div>
                                <h5>{{ $sanction }} Day/s</h5>
                                <h6>Total Absents (Sanctions)</h6>
                            </div>
                            <span class="fa fa-warning"></span>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="pl-4 pr-4 card-list">
                    <div class="modal-header">
                        <h6><span class="fa fa-bell"></span> Announcement</h6>    
                    </div>
                    <div class="modal-body">
                        <table>
                            <thead>
                                <tr>
                                    <td>Announcer</td>
                                    <td>Announcement</td>
                                    <td>Date</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($announcement as $an)
                                        <tr>
                                            <td><h6>{{ $an->announcer }}</h6></td>
                                            <td><textarea class="form-control" readonly cols="30" rows="1">{{ $an->announcement }}</textarea></td>
                                            <td><h6>{{ date('M d, Y', strtotime($an->date)) }}</h6></td>
                                        </tr>
                                    @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <hr>
            </div>
        </div>
        <div class="modal fade" id="accountmanagement">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        
                        <form action="{{ route('student-accountmanagement.update',$info[0]->id) }}" method="post">
                            @csrf 
                            @method('put')
                            <h5><span class="fa fa-gears"></span> Account Management</h5>
                            <hr>
                            <div class="form-group view-student-profile">
                                <img class="cover" src="../addons/assets/img/table1.png" alt="">
                                <img class="profile" src="../addons/assets/root/profiles/{{ $info[0]->profile }}" alt="">
                            </div>    
                            <div class="form-group">
                                <label for="">Student No.</label>
                                <input required readonly value="{{ $info[0]->stuid }}" type="number" name="stuid" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <label for="">Last Name</label>
                                        <input required value="{{ $info[0]->lname }}" type="text" name="lname" class="form-control">
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">First Name</label>
                                        <input required value="{{ $info[0]->fname }}" type="text" name="fname" class="form-control">
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">MI</label>
                                        <input required value="{{ $info[0]->mi }}" type="text" name="mi" class="form-control">    
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Age</label>
                                        <input required value="{{ $info[0]->age }}" type="number" name="age" class="form-control">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Birth Date</label>
                                        <input required value="{{ $info[0]->birthdate }}" type="date" name="bday" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Address</label>
                                <input required value="{{ $info[0]->address }}" type="text" name="address" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Email</label>
                                <input required value="{{ $info[0]->email }}" type="email" name="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="">Year</label>
                                        <select required name="year" id="" class="form-control">
                                            <option selected value="{{ $info[0]->year }}">{{ $info[0]->year }}</option>
                                            @foreach($year as $y)
                                                <option value="{{ $y->yname }}">{{ $y->yname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Section</label>
                                        <select required name="section" id="" class="form-control">
                                            <option selected  value="{{ $info[0]->section }}">{{ $info[0]->section }}</option>
                                            @foreach($section as $s)
                                                <option value="{{ $s->sname }}">{{ $s->sname }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-save"></span> Save Changes</button>
                            </div>
                        </form>
                        <hr>
                        <form action="{{ route('student-signup.update',$info[0]->sid )}}" method="post">
                            @csrf 
                            @method('put')
                            <div class="form-group">
                                <label for="">Create New Password</label>
                                <input required type="password" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="">Retype Password</label>
                                <input required type="password" name="repassword" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary col"><span class="fa fa-save"></span> Save Password</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="profilepicture">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <form action="../addons/file_upload_support/uploadProfile.php?id={{ $info[0]->id }}&profile={{ $info[0]->profile }}" method="POST" enctype="multipart/form-data">
                            <div class="modal-body" style="padding: 10px;">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">Upload</span>
                                        </div>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="new_profile" id="upload" onchange="displayname(this,$(this))">
                                            <label class="custom-file-label" for="upload">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary btn-sm"><span class="fa fa-save"></span> Save</button>
                                <button data-dismiss="modal" class="btn btn-dark btn-sm"><span class="fa fa-times"></span> Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php"?>
        <script>
            <?php
                if(session()->has('student-message')){
                    if(session("student-message")[0] == "welcomeMessage"){
                        echo session("student-message")[0].'("'.session("student-message")[1].$info[0]->fname.'")';
                        session()->forget('student-message');   
                    }else{
                        echo session("student-message")[0].'("'.session("student-message")[1].'")';
                        session()->forget('student-message');     
                    }
                }
            ?>
        </script>
    </body>
    
</html>